#!/usr/bin/env node
/**
 * The desktop's icons, inlined: reads Olivia's PNG artwork from
 * apps/web/public/icons/, scales each down to 128px on its longer side with
 * macOS `sips` (no image library to install) and writes them as data URIs to
 * packages/ui/src/registry/y2k/desktop/icon-data.ts — so the `desktop` item
 * installs as source alone, with nothing to copy into a consumer's public/,
 * as icon-preview.ts does for the pack's Preview icon.
 *
 *   node scripts/desktop-icons.mjs
 *
 * 128px is the biggest a desktop icon is ever drawn (the column inspector's);
 * the Dock magnifies a 64px tile to 128 at most.
 */

import { execFileSync } from "node:child_process"
import fs from "node:fs"
import os from "node:os"
import path from "node:path"

const root = new URL("..", import.meta.url).pathname
const src = path.join(root, "apps/web/public/icons")
const out = path.join(root, "packages/ui/src/registry/y2k/desktop/icon-data.ts")
const SIZE = 128

/** Export name → source file. The folder comes in each tone's colour. */
const ICONS = {
  FINDER: "finder",
  DISK: "disk",
  DOC: "doc",
  NOTE: "note",
  BIN: "bin",
  IPOD: "ipod-icon",
  FOLDER_PINK: "folder-pink",
  FOLDER_AQUA: "folder-blue",
  FOLDER_LIME: "folder-green",
  FOLDER_TANGERINE: "folder-orange",
  FOLDER_GRAPE: "folder-purple",
}

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "desktop-icons-"))
let total = 0
const lines = []
for (const [name, file] of Object.entries(ICONS)) {
  const to = path.join(tmp, `${file}.png`)
  execFileSync("sips", ["-Z", String(SIZE), path.join(src, `${file}.png`), "--out", to], { stdio: "ignore" })
  const b64 = fs.readFileSync(to).toString("base64")
  total += b64.length
  lines.push(`export const ${name} = "data:image/png;base64,${b64}"`)
}
fs.rmSync(tmp, { recursive: true, force: true })

fs.writeFileSync(
  out,
  `/**
 * The desktop's icons: Olivia's own artwork (apps/web/public/icons/), ${SIZE}px
 * on the longer side, inlined as data URIs so they install with the source.
 * Generated by scripts/desktop-icons.mjs — edit the PNGs and run it again.
 */

${lines.join("\n")}
`
)
console.log(`desktop-icons: ${Object.keys(ICONS).length} icons, ${Math.round(total / 1024)} KB of data URIs → ${path.relative(root, out)}`)
