#!/usr/bin/env node
/**
 * Olivia's icon artwork, inlined: reads the pictures in apps/web/public/icons/,
 * sizes each to look as big as the rest (scripts/picture-size.mjs), scales
 * it down to 128px on its longer side (macOS `sips` for a PNG, sharp for a
 * WebP), makes that near-lossless WebP with sharp (which Next
 * installs; no visible pixel moves by more than 1 of 255, at half the bytes
 * of the PNG) and writes them as data URIs, so the items install as source
 * alone, with nothing to copy into a consumer's public/:
 *
 *   desktop/icon-data.ts   what only the desktop draws (Finder, the disk,
 *                          TextEdit, the iPod)
 *   icon-pictures.ts       what the icon set and the desktop both draw (the
 *                          document, the Bin, the star, each tone's folder)
 *   icon-hearts.ts         each tone's heart, for the icon set alone
 *   icon-music.ts          the Music icon, for the icon set alone
 *   icon-preview.ts        the Preview icon, for the icon set alone
 *   icon-quicktime.ts      the QuickTime Player icon, for the icon set alone
 *
 *   node scripts/desktop-icons.mjs
 *
 * 128px is the biggest an icon is ever drawn (the column inspector's); the
 * Dock magnifies a 64px tile to 128 at most.
 */

import { execFileSync } from "node:child_process"
import fs from "node:fs"
import os from "node:os"
import path from "node:path"
import sharp from "sharp"

import { evenSize } from "./picture-size.mjs"

const root = new URL("..", import.meta.url).pathname
const src = path.join(root, "apps/web/public/icons")
const SIZE = 128
const DIR = path.join(root, "packages/ui/src/registry/y2k")

const TONES = { PINK: "pink", AQUA: "blue", LIME: "green", TANGERINE: "orange", GRAPE: "purple" }
const HEARTS = { PINK: "pink", AQUA: "aqua", LIME: "green", TANGERINE: "orange", GRAPE: "red" }
const PNG_NAME = "The name is kept from when it was a PNG, so an icons.tsx from an\n * earlier release still finds it."
/** File → export name → source picture, and what the file says it holds. */
const FILES = {
  "desktop/icon-data.ts": {
    about: "The desktop's own icons",
    icons: { FINDER: "finder.png", DISK: "disk.png", NOTE: "note.png", IPOD: "ipod-icon.png" },
  },
  "icon-pictures.ts": {
    about: "The pictures the icon set and the desktop both draw: the document, the Bin, the star and each tone's folder",
    icons: {
      DOC: "doc.png",
      BIN: "bin.png",
      STAR: "star.webp",
      ...Object.fromEntries(Object.entries(TONES).map(([t, c]) => [`FOLDER_${t}`, `folder-${c}.png`])),
    },
  },
  "icon-hearts.ts": {
    about: "Each tone's heart, for the icon set",
    icons: Object.fromEntries(Object.entries(HEARTS).map(([t, c]) => [`HEART_${t}`, `heart-${c}.png`])),
  },
  "icon-music.ts": {
    about: "The Music icon, a CD under a blue note, for the icon set",
    icons: { MUSIC: "music.png" },
  },
  "icon-preview.ts": {
    about: "The Preview icon, two prints and a loupe, for the icon set",
    note: PNG_NAME,
    icons: { PREVIEW_PNG: "preview.png" },
  },
  "icon-quicktime.ts": {
    about: "The QuickTime Player icon, the Q on a metal player, for the icon set",
    note: PNG_NAME,
    icons: { QUICKTIME_PNG: "quicktime.png" },
  },
}

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "desktop-icons-"))
/** A picture as a near-lossless WebP data URI, sized as the rest, 128px on
 *  its longer side. */
async function dataUri(file) {
  const input = await evenSize(path.join(src, file), "desktop-icons")
  let img = sharp(input).resize(SIZE, SIZE, { fit: "inside", withoutEnlargement: true })
  if (file.endsWith(".png")) {
    const to = path.join(tmp, file)
    fs.writeFileSync(to, input)
    execFileSync("sips", ["-Z", String(SIZE), to, "--out", to], { stdio: "ignore" })
    img = sharp(to)
  }
  return `data:image/webp;base64,${(await img.webp({ nearLossless: true, quality: 80, effort: 6 }).toBuffer()).toString("base64")}`
}

for (const [file, { about, note, icons }] of Object.entries(FILES)) {
  const lines = []
  let total = 0
  for (const [name, pic] of Object.entries(icons)) {
    const uri = await dataUri(pic)
    total += uri.length
    lines.push(`export const ${name} = "${uri}"`)
  }
  fs.writeFileSync(
    path.join(DIR, file),
    `/**
 * ${about}: Olivia's own artwork (apps/web/public/icons/), sized to look as
 * big as the rest, ${SIZE}px on the longer side, as near-lossless WebP,
 * inlined as data URIs so they install with the source.${note ? `\n * ${note}` : ""}
 * Generated by scripts/desktop-icons.mjs — edit the pictures and run it again.
 */

${lines.join("\n")}

/* Patina OS · © 2026 Olivia Forster · MIT licence (DESIGN.md › Licence) · https://github.com/livisliving/Patina */
`
  )
  console.log(`desktop-icons: ${lines.length} pictures, ${Math.round(total / 1024)} KB → ${path.relative(root, path.join(DIR, file))}`)
}
fs.rmSync(tmp, { recursive: true, force: true })
